<a href="https://colab.research.google.com/github/connerdandrews/LinearAlgebra/blob/main/PythonProject1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem 1**

In [31]:
import numpy as np
import sympy as sp

In [32]:
# This code returns the value of the 4th row and 2nd column of a matrix A.
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(A[3,1])

14


**Problem 2**

In [33]:
# This is the original code used to show how to make changes to a matrix. 
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
A[2]=[7,8,10]
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


From the code above we see that the commands change the original matrix to a new matrix where the third row contains the values 7, 8, 10 instead of 7, 8, 9. The command changed the final value in the row. 

In [34]:
# This code adds a new line to the second row of the matrix. 
A[1]=[1, 1, 1]
print(A)

[[ 1  2  3]
 [ 1  1  1]
 [ 7  8 10]]


**Problem 3**

In [35]:
# This is the code given to us in the pdf. 
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
A[1]=A[1]+A[0]*(-A[1,0])
A[2]=A[2]+A[0]*(-A[2,0])
print(A)
A[2]=A[2]+A[1]*(-A[2,1]/A[1,1])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[  1   2   3]
 [  0  -3  -6]
 [  0  -6 -12]]
[[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]


The code above first fills a matrix with values 1-9. Then it does three row replacements. The first row replacement multiplies row 1 by -4 and adds it to row 2. The second row replacement multiplies row 1 by -7 and adds it to row 3. This creates zeros underneath the pivot in the first column. The third row replacement multiplies row 2 by -2 and adds it to row 3 creating zeros all across row 3. 

**Problems 4, 5, and 6**

In [30]:
# This code finds the values of x that solve Ax = b for Problem 4.
A = np.array([[1,2,3],[4,5,6],[7,8,10]])
b = np.array([[-1],[4],[-10]])
x = np.linalg.solve(A,b)
print("X values for the matrix equation:",x, sep='\n')

# This code for Problem 5 checks the values of x we got in Problem 4 to see if they equal b. 
checkB = np.matmul(A, x)
print("b values for the matrix equation:",checkB, sep='\n')

# This code for Problem 6 uses the inverse of A to determine the value of x. 
invA = np.linalg.inv(A)
print("Inverse A:",invA, sep='\n')
checkX = np.matmul(invA, b)
print("Checked X values for the matrix equation:", checkX, sep='\n')

X values for the matrix equation:
[[-14.66666667]
 [ 35.33333333]
 [-19.        ]]
b values for the matrix equation:
[[ -1.]
 [  4.]
 [-10.]]
Inverse A:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
Checked X values for the matrix equation:
[[-14.66666667]
 [ 35.33333333]
 [-19.        ]]


Using the inverse of A we can see that the x values computed in problem 4 were the same as the ones we got when we used the inverse of A.

**Problem 7**

**Problem 8**

In [39]:
# This is all code given to us in the project pdf.
from sympy.abc import a,b,c#allows us to use a,b,c in symbolic calculations
import sympy as sp
M=sp.Matrix([[1,2,3],[4,5,6],[7,8,9]])#note that Matrix is capitalized
print(M)
N=sp.Matrix([[a,0,0],[0,b,0],[0,0,c]])
print(N)
print(M*N)#matrix multiplication can be performed using * in SymPy

M=sp.Matrix([[1,2,3],[4,5,6],[7,8,9]])
print(M.rref())

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Matrix([[a, 0, 0], [0, b, 0], [0, 0, c]])
Matrix([[a, 2*b, 3*c], [4*a, 5*b, 6*c], [7*a, 8*b, 9*c]])
(Matrix([
[1, 0, -1],
[0, 1,  2],
[0, 0,  0]]), (0, 1))


In [44]:
# This code creates a matrix using the formula given to create a 6x6 matrix.Then it row reduces the matrix to RREF. 
M=sp.Matrix([[x+5, x-4, (x-2)**2, x**2, x, 1] for x in [1,2,3,4,5,6]])
print(M)
print("Row reduced Echelon Form:",M.rref(), sep='\n')

Matrix([[6, -3, 1, 1, 1, 1], [7, -2, 0, 4, 2, 1], [8, -1, 1, 9, 3, 1], [9, 0, 4, 16, 4, 1], [10, 1, 9, 25, 5, 1], [11, 2, 16, 36, 6, 1]])
Row reduced Echelon Form:
(Matrix([
[1, 0, 0, 4/3, 4/9,  1/9],
[0, 1, 0, 8/3, 5/9, -1/9],
[0, 0, 1,   1,   0,    0],
[0, 0, 0,   0,   0,    0],
[0, 0, 0,   0,   0,    0],
[0, 0, 0,   0,   0,    0]]), (0, 1, 2))


**Problem 9**

In [47]:
# This code creates a matrix, M, and then finds the determinant for the given matrix. 
M=sp.Matrix([[1, x, x**2, x**3, x**4, x**5] for x in [2,3,4,5,6,7]])
print(M)
determinant = M.det()
print("Determinant of Matrix M:", determinant, sep='\n')

Matrix([[1, 2, 4, 8, 16, 32], [1, 3, 9, 27, 81, 243], [1, 4, 16, 64, 256, 1024], [1, 5, 25, 125, 625, 3125], [1, 6, 36, 216, 1296, 7776], [1, 7, 49, 343, 2401, 16807]])
Determinant of Matrix M:
34560
