<a href="https://colab.research.google.com/github/connerdandrews/LinearAlgebra/blob/main/Python_Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem 1**

In [6]:
import numpy as np
import sympy as sp

A=np.array([[-10,13,7],[2,1,-5],[-6,3,13],[2,1,-5]])
Q,R=np.linalg.qr(A)
print(Q)
print(R)

T = Q.transpose()
B = T@Q
B[abs(B)<1e-12]=0
print(B)

[[-0.83333333 -0.5         0.23570226]
 [ 0.16666667 -0.5        -0.47140452]
 [-0.5         0.5        -0.70710678]
 [ 0.16666667 -0.5        -0.47140452]]
[[ 12.         -12.         -14.        ]
 [  0.          -6.           8.        ]
 [  0.           0.          -2.82842712]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Problem 2**

In [7]:
C=Q@T
C[abs(C)<1e-12]=0
print(C)

[[1.  0.  0.  0. ]
 [0.  0.5 0.  0.5]
 [0.  0.  1.  0. ]
 [0.  0.5 0.  0.5]]


**Problem 3**

In [25]:
A=np.array([[-10,13,7],[2,1,-5],[-6,3,13]])
Q,R=np.linalg.qr(A)


for i in range(0,100):
  Q,R = np.linalg.qr(R@Q)

print('Q value for A100:',Q)
print('R Value for A100:',R)


Q value for A100: [[-1.00000000e+00  5.13850408e-11  2.51830433e-90]
 [-5.13850408e-11 -1.00000000e+00 -2.64357173e-79]
 [-1.10656998e-89 -2.64357173e-79  1.00000000e+00]]
R Value for A100: [[-11.34375689   6.40729937  -8.98940335]
 [  0.           8.78821488 -15.23604746]
 [  0.           0.           1.44445799]]


**Problem 4**

Eigenvalues of A:

-11.343756, 8.788214, 1.444457

**Problem 5**

In [37]:
E, P = np.linalg.eig(A)
print("Eigenvalues",E)


Eigenvalues [-8.78821488 11.34375689  1.44445799]


**Probelm 6**

In [36]:
H = np.array([[1,1,0],
              [1,-1,0],
              [0,1,1],
              [0,-1,-1],
              [1,0,1],
              [1,0,-1]
              ])

H_normed = H / H.max(axis=0)

print("Orthonormal H:",H_normed)

P = H@H.transpose()
print()
print("P",P)

Y = np.array([10,5,9,-1,4,3])
Yhat = P@Y
print()
print("Projection of y onto H:",Yhat)



Orthonormal H: [[ 1.  1.  0.]
 [ 1. -1.  0.]
 [ 0.  1.  1.]
 [ 0. -1. -1.]
 [ 1.  0.  1.]
 [ 1.  0. -1.]]

P [[ 2  0  1 -1  1  1]
 [ 0  2 -1  1  1  1]
 [ 1 -1  2 -2  1 -1]
 [-1  1 -2  2 -1  1]
 [ 1  1  1 -1  2  0]
 [ 1  1 -1  1  0  2]]

Projection of y onto H: [ 37   7  26 -26  33  11]
